version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: voting-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: voting_db
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
        depends_on:
            - db
        networks:
            - voting-network

    nginx:
        image: nginx:alpine
        container_name: voting-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - voting-network

    db:
        image: postgres:15
        container_name: voting-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: voting_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - voting-network

networks:
    voting-network:
        driver: bridge

volumes:
    postgres-data:
